### ISSUE TITLE
Allow a token prop to reference another token prop

### ISSUE THREAD

**Issue by didoo** [salesforce-ux/theo#100]
Currently a token "prop" can reference an alias "prop", so they can share the same value (and in general, multiple tokens can use the same alias).

But I find myself more and more declaring props like this:
```
{
  "global": {
    "type": "token",
    "category": "base",
    "meta": {
      "platform": "mw"
    }
  },
  "aliases": {
    "TOKEN_BORDER_RADIUS": {
      "value": "3px"
    },
    "TOKEN_SPACING_GAP": {
      "value": "15px"
    }
  },
  "props": {
    "TOKEN_BORDER_RADIUS": {
      "value": "3px"
    },
    "TOKEN_SPACING_GAP": {
      "value": "15px"
    }
  }
}
```
because I need not only to declare a "token" but also to use that value in other tokens (imagine using the border radius in a "buttons" token group).

What I am suggesting is to allow token _props_ not only to reference _aliases_ like in this case, but also other _tokens_ (a-la-Sass, to be clear: something like a variable referencing another variable).

Now, in this case I see two possible options: 

1) use a different syntax to reference another _prop_, as compared to the one for the _alias_:
```
"TOKEN_COLOR_X": {
  "value": "{!ALIAS_COLOR_X}"
}
```
vs
```
"TOKEN_COLOR_X": {
  "value": "{$TOKEN_COLOR_Y}"
}
```

2) use the same syntax to reference both _aliases_ and _props_:
```
"TOKEN_COLOR_X": {
  "value": "{!ALIAS_COLOR_X}"
},
"TOKEN_SIZE_A": {
  "value": "{!TOKEN_SIZE_B}"
}
```

The pro of the first implementation is that is 100% safe, since is a new syntax will be backwards compatible. The con is that is a new syntax to add, increasing the complexity of the API.

The pro of the second implementation is that "it just works" and is simple to understand (the complexity will be in the implementation of the logic behind, but that's another story). The con is that in some case could conflict with the previous version of the API (think the example of a token prop referencing an alias with the same name: now we don't have problems, with this change it would raise a conflict). 

What do you think? Ideas, opinions, reasons why it would be a bad idea?

Also, open for discussion: will a token prop referencing another token prop inherits its extra attributes (type, category, metas, etc.)? Which by the way is the same question I have about aliases, but is not yet totally clear to me what is the expected behaviour :)

**Comment by kaelig** [comment]
I think this is a great idea but it definitely adds potential complexity:

1. With great power comes great responsibility: it becomes easier to make a mess and build complex architectures
2. There's no authoring tooling around Theo (e.g. a UI, or extensions for Atom, Sublime, VS Code…), so managing tokens becomes exponentially more complex if we make it possible to cross-reference tokens between them or even aliases to reference tokens

I'm all for improving workflow, but also believe there is beauty in constraints.

That's my 2 cents, I'm curious to see what other people think.

**Comment by micahgodbolt** [comment]
Another challenge is that when referring to aliases we use `{!COLOR_X}`, which does not indicate whether that is an alias or prop. I.E. we'd have to introduce a way to differentiate between COLOR_X the alias, and COLOR_X the prop.

TBH, I added the ability for alias to reference aliases, so I know it wouldn't be TOO hard to do the same to props. This could even be written as a jsonPreProcess, so that you resolve your props-aliasing-props before Theo even sees the data.

**Comment by micahgodbolt** [comment]
Here's an example of jsonPreProcess

https://gist.github.com/micahgodbolt/96c9cf35a6fe24d29f6886f47f30f8c8#file-nested_props_theo_transform-js

**Comment by kaelig** [comment]
@aputinski @srohde any thoughts on this?

**Comment by limitlessloop** [comment]
Should be re-considering how aliases work? They seem like just another layer of abstraction within an already abstracted concept (design tokens). I would find it much easier to just reference/import design tokens within design tokens, but then I know little of the use cases which aliases are used in. However with the small number of times I need to use aliases they seem more complicated than they ought to be.
