### ISSUE TITLE
Allow an imported alias/prop to be overridden by a locally defined alias/prop with the same name

### ISSUE THREAD

**Issue by beauroberts** [salesforce-ux/theo#104]
Hey guys! Thanks again for a great tool that we make use of every day.

I noticed in the 6.0 alpha that an imported alias/prop will override a locally defined alias/prop with the same name (see [`mergeImports`](https://github.com/salesforce-ux/theo/blob/master/lib/definition.js#L135)). Was that intentional? If not, it would be cool if the locally defined aliases and props could override the imported ones. We currently use this kind of behaviour for theming - there's a default theme and other themes can apply changes on top of it without having to redefine *all* of the aliases.

**Comment by kaelig** [comment]
Thanks for the kind words, @beauroberts! And glad Theo is useful to you and your team, that's always good to hear :)

What you describe makes total sense (looks like a regression). I'm going to work on it tomorrow, do you have time to put together a failing test in a pull request? I'll attempt to make it pass.

**Comment by beauroberts** [comment]
Done @kaelig! Thanks for jumping on this so quickly.
