### ISSUE TITLE
css modules format

### ISSUE THREAD

**Issue by nickbalestra** [salesforce-ux/theo#110]
I was thinking of working on a PR for adding format support for [css modules ](https://github.com/css-modules/css-modules). What you think?

**Comment by aputinski** [comment]
This sounds great, can you sketch out roughly what the output would look like?

**Comment by nickbalestra** [comment]
Sure, following the spec for [values variables in css-modules](https://github.com/css-modules/css-modules/blob/master/docs/values-variables.md) the output could look something like:

### cssmodules.css

```
/* If prop has 'comment' key, that value will go here. */
@value $prop-name: PROP_VALUE;
```

**Comment by aputinski** [comment]
This looks great. I did a bunch of cleanup today, so adding a new format + test should be pretty simple. Let me know if you need any help.
