### ISSUE TITLE
Theo-cli

### ISSUE THREAD

**Issue by nickbalestra** [salesforce-ux/theo#113]
Hi @aputinski ,
I'm putting together a little CLI tool around Theo and I wanted to share it here.

https://github.com/opentable/design-tokens/tree/master/tools/theo-cli

**Comment by aputinski** [comment]
This is great! Would you be interested in submitting a PR to add CLI directly in theo?

**Comment by nickbalestra** [comment]
That will be awesome, so that by installing Theo it will automatically come with a CLI tool :)
We could add a `cli` folder inside `/lib`, what you recon?

**Comment by aputinski** [comment]
I think most projects that have a CLI contain a top-level `bin` directory, and then in `package.json` you can specify `"bin": "bin/theo.js",` which would the parse `argv`, etc

**Comment by nickbalestra** [comment]
Great, [that's](https://github.com/opentable/design-tokens/blob/master/tools/theo-cli/package.json#L10) how I did it as well.

I'll work on a PR for it in the upcoming days
