### ISSUE TITLE
Can I register a new transform using the CLI?

### ISSUE THREAD

**Issue by tomger** [salesforce-ux/theo#123]
I'd like to append sp/dp to my Android font sizes.

> $theo tokens.yml --transform android,myCustomTransform --format android.xml

It looks like I can create JS files with transforms in the "./transforms" folder, but that I can't create new groups like "myCustomTransform" that trigger the valueTransform.

**Comment by aputinski** [comment]
Currently, to use `registerValueTransform` and `registerTransform` you need to use the node API

**Comment by tomger** [comment]
Would you accept a PR that would allow the CLI to load custom value transforms from a JS file?

Theo could detect JS files like your [Android Unit example](https://github.com/salesforce-ux/theo/issues/124#issuecomment-338361044) in "./transforms" and then then CLI be could called like:
> theo tokens.yml --transform android --format android.xml

**Comment by aputinski** [comment]
Yeah, I think that's a good idea. Maybe it could look like this:
```bash
theo tokens.yml --setup theo.setup.js --transform android --format android.xml`
```
where `--setup` would be a path to a file that will be required before processing the rest of the flags and allow you to register any additional transforms / formats?
