### ISSUE TITLE
What are aliases?

### ISSUE THREAD

**Issue by morewry** [salesforce-ux/theo#125]
I find myself pretty confused by aliases and uncertain where to get clarification on their purpose.

An alias, in US English, means "a name someone is otherwise called or also known as, an additional name that a person sometimes uses." In people terms, an alias is not the legal or official name of the person--basically, it's not their canonical name within the social system.

So when I started experimenting, I approached it from that perspective:

```json
{
  "props": {
    "cloudBurstBlue": {
      "value": "#20315A"
    }
  },
  "aliases": {
    "blue": "cloudBurstBlue"
  }
}
```

My intention was to set up a canonical name for a color, e.g. `cloudBurstBlue`, within the design system. Then, I wished to create aliases for that color, alternative names by which that color might called at other times within implementations, e.g. `blue`. 

The output I got was this:

```css
:root {
  --cloud-burst-blue: #20315A;
}
```

No alias in the output, which was disconcerting. Can't use the alternative name if it's not present, after all. In trying to figure out what I did wrong, I began to get the impression that values, if I wish to reuse them under other names, have to be set up in the aliases--exactly the opposite way from my intuition and with a special syntax:

```json
{
  "props": {
    "blue": {
      "value": "{!cloudBurstBlue}"
    }
  },
  "aliases": {
    "cloudBurstBlue": {
      "value": "#20315A"
    }
  }
}
```

Then the output I got was this:

```css
:root {
  --blue: #20315A;
}
```

I only get one name in my result again. So I infer the alias feature is a preprocessor-style feature; it gets compiled away by Theo. (Which I also found somewhat unexpected for no particular reason.)

Is my new understanding of "aliases" as a compile-time-only feature that allows an "alias" to be used to reference its own value an accurate one?

**Comment by aputinski** [comment]
Thanks for the feedback. After reading your comments, I agree that `aliases` is probably a misleading name. 

>  So I infer the alias feature is a preprocessor-style feature; it gets compiled away by Theo.

You are exactly right. "aliases" are variables that can be referenced inside of "props" and other "aliases" using the `{!}` syntax and are then replaced during the compilation process. "variables" would probably be a more appropriate name. Sorry for the confusion.

If you have time, a PR to the README would be greatly appreciated.

**Comment by morewry** [comment]
Thanks as well! Later I recognized a couple places in the README that should have given me hints (I ended up looking at some issues and PRs, hah), but it could be clearer. I'll see if I can make a PR soon.
