### ISSUE TITLE
Misspelled `font-families` type parameter in render function

### ISSUE THREAD

**Issue by MindSculpt** [salesforce-ux/theo#128]
First off — thanks for posting this repo. Awesome way to think about handling a design system's config single source of truth for settings.

I did some digging into the code since there isn't any documentation on the types of categories you can add. I noticed on line `321` of `lib/formats/html.js` that:

`${this.renderSection('font-families', 'Font Families')}`

...should actually be:

`${this.renderSection('font-family', 'Font Families')}`

Just a simple spelling change is needed here. Happy to do a pull request if needed.

PS — Any existing way to output kebab case values in the `app.html` file instead of camel case?

**Comment by aputinski** [comment]
If you don't mind making a PR, that would be great! As far as the html template, you'd probably need to register your own format, but you can use `lib/formats/html.js` as a starting point.
