### ISSUE TITLE
Question: What is the animations format?

### ISSUE THREAD

**Issue by equinusocio** [salesforce-ux/theo#134]
Hi, i have a prop `fadeIn`, what is the starting animation format? a css keyframes?

**Comment by aputinski** [comment]
There's no set convention for animations.. totally depends on how you plan to implement animations in your system.

**Comment by equinusocio** [comment]
So, we need to implement a formatter that transform the value for each platforms, it is right?

**Comment by aputinski** [comment]
The formatter is responsible for the final output, but you're probably looking for transforms. Unfortunately, they're not very well documented. There is a concept of a transform which is made up of several value transforms.

For instance, we have a value transform called `unit/pixelValue` which will take a rem value and convert it to a pixel value (number) without the "px" suffix.  https://github.com/salesforce-ux/theo/blob/master/lib/transforms/unit.js#L23

Once you have created some value transforms using `theo.registerValueTransform` (https://github.com/salesforce-ux/theo#api), you can call `theo.registerTransform` which is a collection of value transforms that can be used when calling `theo.convert`.

As an example, we have registered a transform called `android` https://github.com/salesforce-ux/theo/blob/master/lib/register.js#L124.

In the case of animation, you can register some value transforms that will translate your animation properties into android specific value.

Hope that helps.

**Comment by equinusocio** [comment]
Yes, thank you. 👍🏻
