### ISSUE TITLE
Unable to setup multiple custom formats using CLI

### ISSUE THREAD

**Issue by morewry** [salesforce-ux/theo#145]
I will be setting up at least three custom formats for a set of tokens and ran into what appears to be a limitation in the CLI.

### Comma Separated 1

First, trying comma separated values like used for multiple formats,

**Input**
```shell
theo ./tokens.json --setup ./build/elementFormat.js,./build/previewFormat.js --format map.scss,module.js,ce.js,preview.html --dest $(pwd)
```

**Output**
```
Error: Cannot find module '/Users/morewry/project/build/elementFormat.js,./build/previewFormat.js'
```

### Comma Separated 2

Second, adding a space,

**Input**
```shell
theo ./tokens.json --setup ./build/elementFormat.js, ./build/previewFormat.js --format map.scss,module.js,ce.js,preview.html --dest $(pwd)
```

**Output**
```
Error: Cannot find module '/Users/morewry/project/build/elementFormat.js,'
```

### Space Only

**Input**
```shell
theo ./tokens.json --setup ./build/ceFormat.js ./build/previewFormat.js --format map.scss,module.js,ce.js,preview.html --dest $(pwd)
```

**Output**
```
💩  Oops, something went wrong: Error: Format "preview.html" is not registered
```

### Multiple Options

**Input**
```shell
theo ./tokens.json --setup ./build/elementFormat.js --setup ./build/previewFormat.js --format map.scss,module.js,ce.js,preview.html --dest $(pwd)
```

**Output**
```
TypeError: Path must be a string. Received [ './build/elementFormat.js', './build/previewFormat.js' ]
```

Looks to me like this isn't a part of the CLI implementation so far based on:

It takes in optimist's parsing of setup:

https://github.com/salesforce-ux/theo/blob/c450de1ffb9f0cbf01b5bcea96ce88ec69d12a54/bin/theo.js#L12

Then tries to require it as a module:

https://github.com/salesforce-ux/theo/blob/c450de1ffb9f0cbf01b5bcea96ce88ec69d12a54/bin/scripts/build.js#L8-L12

Tests show only a single custom format:

https://github.com/salesforce-ux/theo/blob/c450de1ffb9f0cbf01b5bcea96ce88ec69d12a54/bin/__tests__/theo.spec.js#L55-L61

I'd be happy to pull request this if you can tell me what approach you'd like to support. I'd lean toward **Comma Separated 1** because it is the same as the syntax for multiple formats, but it'd be trivial to support both that and **Multiple Options**.

**Comment by aputinski** [comment]
I think the recommended approach would be to register all transforms in the same file. If you want to split then up in different files, you can just require them from the setup file.

**Comment by CH-RhyMoore** [comment]
Yeah, I definitely don't want to register them in the same file. Some of the formats will be broken out into their own npm packages.

If I'm understanding you correctly, you're saying that to register and use multiple custom formats, we should create setup file specifically to aggregate the formats, e.g.

```js
const elementFormat = require('./build/elementFormat');
const previewFormat = require('./build/previewFormat');

module.exports = function (theo) {
  elementFormat(theo);
  previewFormat(theo);
};
```

**Comment by aputinski** [comment]
Yeah, that was the original idea.
