### ISSUE TITLE
Alias calculations

### ISSUE THREAD

**Issue by NoWorries** [salesforce-ux/theo#149]
Is it possible to use calculations, for example to create a range of sizes based on a single alias?

**_aliases**

base-spacing:
    value: "8px"

**_props**

spacing-default:
    value: "{!base-spacing}"

spacing-large:
    value: "{!base-spacing} * 2"

**resolves to:**

spacing-default: 8px
spacing-large: 16px

**Comment by aputinski** [comment]
This is not currently supported

**Comment by aputinski** [comment]
I'd like to start thinking about a proposal for adding this type of functionality though
