### ISSUE TITLE
Hyphen (-) not a valid character for token names in Android?

### ISSUE THREAD

**Issue by morewry** [salesforce-ux/theo#158]
I recently began working with our Android team on using the `android.xml` format. They've reported to me that `-` (hyphen) is not a valid character for names, e.g.

```
<color name="PROP-NAME">
```

Is not valid. I am using hyphens in our token names and the `android.xml` format output leaves them as hyphens. If hyphens aren't valid, I'd expect this format to remove them or change them to underscores, much like the `module.js` format changes names to camel case.

Be happy to PR that if it makes sense.

Slightly related, the `android.xml` format transforms token names to UPPERCASE. Why is that?

**Comment by aputinski** [comment]
Yeah — a PR would be great. I'm planning on making a major release because there were several other breaking changes introduced for Android recently. As far as the name case, I'm not quite sure.

**Comment by morewry** [comment]
I won't touch the casing, then, for now.
