### ISSUE TITLE
Improve documentation for `html` under Formats

### ISSUE THREAD

**Issue by geraldfullam** [salesforce-ux/theo#163]
I discovered through trial that when using `theo` to build `html` that some categories of tokens were not rendered to the page. Upon [examining the source code](https://github.com/salesforce-ux/theo/blob/master/lib/formats/html.js#L419-L448), I learned that these categories are conditionally rendered and that each is mapped to a human-friendly display name.

I propose mentioning this conditional rendering and explicitly listing the supported categories and their mapped display names (and perhaps in the future making this configurable via options).

Also, the comment in the example for passing additional options for the `html` format implies that there are more than just the one `transformPropName` shown, but upon [examining the source code](https://github.com/salesforce-ux/theo/blob/master/lib/formats/html.js#L11-L13) it appears that this is the only additional configurable option at this time.

I propose explicitly listing the configurable option(s) in the documentation.

**Comment by aputinski** [comment]
I totally agree. Would you mind submitting a PR?
