### ISSUE TITLE
Update package.json? 

### ISSUE THREAD

**Issue by arnthor3** [salesforce-ux/theo#179]
I have been getting npm audit warnings regarding two of Theo dependencies, js-yml 3.10. and handlebar-helpers. Is this something that should/can be fixed?
*Using version 8.1.2 of Theo*

**Comment by lautr** [comment]
#### js-yml
I created a PR to update js-yml: https://github.com/salesforce-ux/theo/pull/181

####  handlebar-helpers
The handlebar-helpers issue is due to a deep dependency there is an open issue on their end to fix it: https://github.com/helpers/handlebars-helpers/issues/342

**Comment by arnthor3** [comment]
Just waiting on the new release.

**Comment by aputinski** [comment]
Just published `8.1.3`. Sorry for the delay.
