### ISSUE TITLE
Support for Typescript

### ISSUE THREAD

**Issue by ringodotnl** [salesforce-ux/theo#180]
Hello, 

Are you planning to support typescript as output format ?

Cheers,
Ringo.

**Comment by petekp** [comment]
@ringodotnl Hi, can you describe in more detail what you would like to have the output be? I might be able to help you since I'm working with Theo in a TS context.

**Comment by aputinski** [comment]
I don't have any plans to add TypeScript as a format, but I think @petekp and others have been discussing it here https://github.com/salesforce-ux/theo/issues/174
