### ISSUE TITLE
Support CSS Custom Properties for Cascading Variables Module Level 1

### ISSUE THREAD

**Issue by srohde** [salesforce-ux/theo#20]
http://www.w3.org/TR/css-variables/

Example:

```
:root {
  --main-color: #06c;
  --accent-color: #006;
}
/* The rest of the CSS file */
#foo h1 {
  color: var(--main-color);
}
```

**Comment by lozandier** [comment]
I was just going to file an issue about this; is it naive to think it'll get solved along the lines of doing this out-of-the-box? 

```js
// Written w/ ES6 JS 
theo.registerFormat('css-props', (json, options) => {
  return json.propKeys.map(key => {
    let prop = json.props[key];

   //  assuming lodash is imported as a ES6 module, required by NPM 
   let kebabedName = _.kebabCase(prop.name); 
   return `--${kebabedName}: ${prop.value};`;

  }).join('\n');
});

```

**Comment by kaelig** [comment]
Hey @lozandier, apologies for the (long) wait. Feel free to open a Pull Request, we'll definitely consider it!

**Comment by lozandier** [comment]
@kaelig Understood; I've started a PR to get the ball rolling on this.

**Comment by NameFILIP** [comment]
@lozandier Are you still planning to submit a PR for this?

**Comment by lozandier** [comment]
Yeah; I've been blocked from going back to it because of tight deadlines at
work & other PRs & issues I've sent to public & private Github repos.

On Friday, June 10, 2016, Filip Spiridonov <notifications@github.com> wrote:

> @lozandier <https://github.com/lozandier> Are you still planning to
> submit a PR for this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/salesforce-ux/theo/issues/20#issuecomment-225291692>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABKqOE2DpxqXqzTEP-npzgpQ28Ab57rVks5qKc2RgaJpZM4CcuK0>
> .
>


-- 
Kevin Lozandier
lozandier@gmail.com <lozandier@gmail.com>
