### ISSUE TITLE
Missing dependency to "optimist" package

### ISSUE THREAD

**Issue by notbear** [salesforce-ux/theo#216]
The theo.js script requires an _optimist_ package but _optimist_ is not listed as a direct dependency in package.json.

It usually works because _optimist_ can be installed via transitive dependency from _handlebars_ package. 

It fails when using latest _handlebars_ (4.7.4+) as they [migrated from deprecated _optimist_ to _yargs_](https://github.com/wycats/handlebars.js/pull/1666)

**Comment by lalizita** [comment]
is this fixed?

**Comment by frebro** [comment]
Nope. Waiting for merge. I can confirm the fix in the pull request works.

**Comment by rivajunior** [comment]
can anyone make a version with this fix?

**Comment by Azlan-JG** [comment]
Can confirm I am still seeing this issue

**Comment by gg-justgiving** [comment]
I am also still seeing this issue - when will this be resolved @zahnster

**Comment by frebro** [comment]
Merged in #217 but still waiting for a new version to be published. 

For anyone having problems, the temp fix is to install Theo and then edit _node_modules/theo/bin/theo.js_ on **L5** from `const argv = require("optimist").argv;` to `const argv = require("yargs").argv;`. You may need to `npm install yargs` depending on what other modules you have installed.

**Comment by LolliDepp** [comment]
@frebro modifying node_modules files directly is not a temp fix since on every `npm install` on CI machines that change will be removed

**Comment by notbear** [comment]
@zahnster @aputinski any chance for the release? 

BTW What are Salesforce's plans regarding this project? Is it abandoned? 
It's really nice tool. IMO better than Style Dictionary for example. But I'd have to consider migration if Theo stays unmaintained.

**Comment by frebro** [comment]
> @frebro modifying node_modules files directly is not a temp fix since on every `npm install` on CI machines that change will be removed

Sorry, I was being unclear. A temp fix **when using Theo CLI manually from the command line** is to install yargs and edit theo.js. It works, but will not persist on CI obviously.

**Comment by ringodotnl** [comment]
npm i of theo version 8.1.5 doesn't have the merged change for some reason so:
const argv = require("optimist").argv; to  <--- that's in 8.1.5
const argv = require("yargs").argv; <-- should be that

Can you (re)publish the npm again ?

**Comment by notbear** [comment]
@ringodotnl My fix was merged long time ago. But there was no release from January. Seems the project has been abandoned by its maintainers. Sad.

**Comment by ringodotnl** [comment]
@notbear cheers for the reply.
Hopefully they find the time to make a new release, for now we apply a patch.
