### ISSUE TITLE
[suggestion] exclude/include variables for certain platforms

### ISSUE THREAD

**Issue by javoire** [salesforce-ux/theo#26]
If the visual guidelines have specific rules for certain platforms
```json
{
  "name": "GRAY_12",
  "value": "hsv({!GRAY_HUE}, {!SAT_20_AND_BELOW}, 12%)",
  "category": "color",
  "exclude": ["ios"]
}
```

**Comment by aputinski** [comment]
Hey @javoire, I'm currently working on a complete refresh of the Theo API and I'll take this use case into account!

**Comment by javoire** [comment]
That's great to hear!

Cheers
