### ISSUE TITLE
[question] Possible to change output value in templates?

### ISSUE THREAD

**Issue by eldh** [salesforce-ux/theo#31]
I'm trying to understand how I can get stuff like gradients and transition easings to work well across platforms. 

For example, I want this in my scss:
```$transition-easing: cubic-bezier(.23,1,.32,1);```

And in the json I want this:
```"transitionEasing": [.23,1,.32,1]```

Currently working around it by just setting ".23,1,.32,1" as the value and then wrapping it in functions in scss and js. That becomes especially ugly in js, as value can only be strings so I have to manually split and parseFloat.

Is this possible to do this in a nicer way? How?

**Comment by aputinski** [comment]
Hey @eldh,

Just wanted to let you know that I'm currently working on a complete refresh of the Theo API which will make what you're talking about much simpler.

The API will look something like this:

```js
registerValueTransform('gradient',
  // Only run the transform on props that match the filter
  prop => prop.type === 'gradient',
  // Return the transformed value
  prop => {
    let [a,b,c,d] = prop.value;
    return `cubic-bezier(${a}, ${b}, ${c}, ${d})`
  }
);
```

I'm hoping to have this published in the next few weeks.

Let me know if you have any thoughts on the API.

**Comment by eldh** [comment]
Awesome. I think that looks great!
