### ISSUE TITLE
Add possibility to return converted result instead of writing to file.

### ISSUE THREAD

**Issue by Chrazy** [salesforce-ux/theo#32]
Not sure if this is possible already but I wonder if it would be possible at all to return the converted result so it can be used immediately and not write it to a file.

**Comment by Chrazy** [comment]
Looking through the code I noticed that convert actually returns the compiled result, like I wanted. Would it be possible to just add an option/flag not to write it to a file?

**Comment by aputinski** [comment]
@Chrazy I'm getting ready to release Theo 3.0.0 and I'll make sure this is possible with the new API

**Comment by Chrazy** [comment]
Cool! One other thing that popped up on my wish list was the ability to send in actual source (not a path, but content). I haven't had time to look through the changes yet but maybe that's possible now too?
