### ISSUE TITLE
Output HTML using hyphened format instead of Aura camelCase

### ISSUE THREAD

**Issue by interactivellama** [salesforce-ux/theo#45]
Maybe I'm missing something obvious, but how to I change the HTML outut from Aura to LESS formatted variables?

**Comment by kaelig** [comment]
Hey! Is this still a use case you need to address?

**Comment by interactivellama** [comment]
It's been 6 months since I've regularly used Theo do to shift in priorities. Does Theo output the HTML sample of the design tokens that uses the "web/hypenated" version of the class names now?

**Comment by kaelig** [comment]
Just confirmed that it still outputs the camelCase format. Not sure this is something we need to address at the moment so I'll close this.
