### ISSUE TITLE
Allow aliases to rely on other aliases

### ISSUE THREAD

**Issue by faboweb** [salesforce-ux/theo#46]
Hi,
when I want to define aliases dependent on aliases. Those are not resolved:

```
aliases: {
  BASE-LINE-HEIGHT: "1.5";
  BASE-SPACING: "{!BASE-LINE-HEIGHT} * 1em";
  SMALL-SPACING: "{!BASE-SPACING} / 2";
}
```

resolves to:
  `$small-spacing: {!BASE-LINE-HEIGHT} * 1em / 2;`

**Comment by kaelig** [comment]
Thank you, @faboweb. This is a known limitation, but feel free to submit a pull request!

**Comment by micahgodbolt** [comment]
@faboweb would love a review of my current PR. Does that meet your needs?

**Comment by kaelig** [comment]
This feature was just added in v5.0.0-beta.3!

**Comment by jina** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9941970-157611153_2-s1-v1.png?transparent=1&width=246)
