### ISSUE TITLE
YAML vs YML file extensions

### ISSUE THREAD

**Issue by micahgodbolt** [salesforce-ux/theo#60]
I made the mistake of using a .yaml extension and got an error of ` Cannot read property 'props' of undefined`. I'm guessing it only checks for yml? Would be nice to support both, or at least give proper error message if .yaml.

I might try to tackle this if you have a preference on which approach.

**Comment by aputinski** [comment]
I'm fine with supporting both extensions. Looks like you'd just need to update two things:

https://github.com/salesforce-ux/theo/blob/794bede53b15d432793906423017cac42a3f7799/src/props/util/index.js#L29

https://github.com/salesforce-ux/theo/blob/794bede53b15d432793906423017cac42a3f7799/src/props/index.js#L494

**Comment by kaelig** [comment]
See #61

**Comment by kaelig** [comment]
This was added in v5.0.0-beta.2
