### ISSUE TITLE
How to change the generated tokens to use camelCase style as opposed to hyphen-separated

### ISSUE THREAD

**Issue by julianomoreira** [salesforce-ux/theo#90]
Hello peeps,

My team is doubling down on our standards and we're changing our classes to use camelCase (buttonLarge) as opposed to hyphen-serated words (button-large). Is there a way to change the output of tokens to use camelCase style? 

Thanks,

-Juliano

**Comment by kaelig** [comment]
Thanks for using Theo, @julianomoreira!

### In Theo v5

This is documented here: https://github.com/salesforce-ux/theo#example-6

```js
theo.registerFormat('scss-camel', (json, options) => {
  return json.propKeys.map(key => {
    const prop = json.props[key]
    return `$${_.camelCase(prop.name)}: ${prop.value};`
  }).join('\n')
})
```

### In Theo v6

No documentation yet, but here's what it should look like:

```js
    theo.registerFormat('scss-camel', `
        {{#each props as |prop|}}
          ${{camelCase prop.name}}: ({{prop.value}});
        {{/each}}
    `)
```

**Comment by julianomoreira** [comment]
Thanks! Helpful. We're using Theo 5.
